### ISSUE TITLE
PR受け付けの状況についての質問と相談

### ISSUE THREAD

**Issue by smdn** [HiroyukiSakoh/EchoDotNetLite#9]
現在、EchoDotNetLiteに対して複数の修正を行っていて、その変更をこちらにもマージしたいと考えています。

それにあたって質問なのですが、今後複数件のPull Requestを送った場合、またそれに付随するやり取りに関して、どの程度対応していただけるでしょうか?
あるいは、現時点で本プロジェクトに対しては、どの程度注力されている/するつもりでおられますでしょうか?

レビューやマージ作業等でそれなりの期間と労力をいただくことになると想定されるため、今回事前にご相談させていただく次第です。

想定している作業手順としては、以下のような流れを考えています。
+ まずは受け入れ可能な変更・マージする変更についてのすり合わせを行う
+ 後述する作業ブランチから変更を切り出してPRを作成、レビュー、マージ
+ 上記を繰り返す

私が行った変更内容は、[作業ブランチ](https://github.com/smdn/EchoDotNetLite/commits/devel)と[masterとの差分](https://github.com/smdn/EchoDotNetLite/compare/master..devel)にてご覧いただけます。
主な変更内容を抜粋するとざっと以下のとおりで、ここからトピックごとにPRを作成・マージする流れを考えています。

- .NET Coreから.NETへの移行、およびコードのモダン化
  - NewtonsoftJsonからSystem.Text.Jsonへ移行
  - `byte[]`から`(ReadOnly)Memory<byte>`へ
  - `CancellationToken`によるキャンセルのサポート
  - nullability annotationsの追加
  - `ObservableCollection<T>`への置き換え
- EchoDotNetLite.SpecificationsのMasterDataのアセンブリ埋め込みリソース化
- 仕様に対応するクラスをはじめとする、各種クラスの読み取り専用化・不変クラス化
- IPANAClientインターフェイスの名称とシグネチャ整理
- 命名ガイドラインに従った公開APIの改名
- テストの追加(NUnit)
- その他改善・リファクタリング

これに加えて、上記変更のマージののちに、NuGetパッケージでの配布も行っていただきたいとも考えています。

一方で、現在本プロジェクトに対しては積極的でないようでしたら、現在のフォークで継続して開発を行うことを検討しています。
その場合でも、NuGetパッケージのリリースを検討していて、リリースにあたって名称の変更や権利表記等で事前に確認を取りたいことが何点かありますので、その際には改めてissueを立てます。

以上長くなりましたが、本プロジェクトの活動とcontribution受け付けについて、現況とお考えをお聞かせいただけますと幸いです。
よろしくお願いします。

**Comment by smdn** [comment]
現在こちらのプロジェクトの活動は積極的ではないと考え、勝手ながらこちらからフォークした以下のリポジトリにて開発を継続させていただくことといたしました。

[smdn/Smdn.Net.EchonetLite](https://github.com/smdn/Smdn.Net.EchonetLite)

それに関して、以下お知らしておきたいことがありますので、ご一読いただけますと幸いです。　なお、特に不都合などがなければ返信等は不要です。　一方、なにかありましたら対応いたしますので、その際はご返答ください。

- ソースファイルに著作権表記を追記させて頂きました (smdn/Smdn.Net.EchonetLite#1)
  - SPDXを用いて、全ソースファイルに原著作者の情報を記載させていただきました
  - 本来ならオリジナルの著作者自身に記載してもらうのが望ましいものですので、もし差し支えなければ、上記PRに対して記載内容に問題ないことの確認をコメントとして残していただけますと幸いです
- リポジトリ名・プロジェクト名を`Smdn.Net.EchonetLite`に変更しました (smdn/Smdn.Net.EchonetLite#8)
  - フォークでの改変を行うにあたり、今後想定される`EchoDotNetLite`との名前の混同や、名前の使用に関する争議、その他の混乱を避けるため、別の名前を使用させていただくこととしました
  - また、上記名称にてNuGetパッケージをリリースさせていただきました: [NuGet Smdn.Net.EchonetLite](https://www.nuget.org/packages/Smdn.Net.EchonetLite)
- 現在送らせていただいているプルリクエストを取り下げました
  - ブランチを整理する都合上、PRを送るのに使用したブランチを一旦削除し、 #7 および #8 をクローズしました
  - もし今後変更を取り込んでいただけるようでしたら、改めてPRを作成いたしますので、ご連絡ください

以上をもって本質問はクローズとしたいと思います。　お読み頂いてありがとうございました。

**Comment by HiroyukiSakoh** [comment]
応答できず、申し訳ありません。
リポジトリのWatch設定が、`participating and @mentions`となっていたため全く気付いていませんでした。

フォーク等に関してのコメントも確認しました。
ソースへの追記などもありがとうございます。特に異存ありません。

あまり時間はさけないので、Contributorを付けてリポジトリごとお任せする くらいだったらできたかと思いますが、今更ですね… すみません。
PR頂いていたものは、githubにあげてなかった.net8化分のpushと同時に取り込ませていただきました。

別のプロジェクトでこのソースを直接使用しているので、
時間が出来たら、公開されるパッケージに切り替えようと考えています。
（その際はこのリポジトリはアーカイブすると思います）

このライブラリを作った時から大分状況は変わり、AIFは公開されているし、
[Machine Readable Appendix](https://echonet.jp/spec_mra_rr2/)もあるので、
自前のマスターよりは上記を参照する形に作り替えられたらな という思いはありました。(参考まで

**Comment by HiroyukiSakoh** [comment]
1点 フォークのコミットを見ていて思い出したので共有です。

法律は詳しくないですが ECHONET Lite 商標の使用を避けるため、
あえてEchoやEchoDotNetLite等の名前付けに、初期実装後公開前に無理やり置換した記憶があります。
（なので、名前付けが全体的に中途半端でイマイチな状態になっていた
（Smdn.Net.と付けたことで回避できるのかもしれませんが

**Comment by smdn** [comment]
ご返答いただきましてありがとうございます。

まずはフォークに関してご確認いただきありがとうございます。
あまり時間は取れないとのことなので、引き続きフォークにて独立して作業を続けさせていただこうと思います。
もし何かありましたら、ご連絡ください。
また今後またバグ等を見つけたら、その際はIssueあるいはPRにて報告させていただきます。

商標に関する懸念についても、コメントいただき恐縮です。
ご指摘のとおり、``Smdn.Net.``のプレフィックスをつけていることに加え、Pascal Caseに変えていることから、私としては恐らく商標に関するトラブルは避けられるのではないかと考えています。
(無論、エコーネットコンソーシアムから求めがあれば、名称変更等を行うつもりではいます。)
